# Generated by Django 5.1.4 on 2025-01-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "hashed_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
