# Generated by Django 5.1.4 on 2025-01-17 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_userpreferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("company_name", models.TextField(blank=True, null=True)),
                ("company_url", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                (
                    "years_experience",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("skills", models.JSONField(blank=True, null=True)),
                ("salary", models.CharField(blank=True, max_length=100, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Indeed', 'LinkedIn', 'Gmail', etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gmail_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique Gmail message ID if fetched from Gmail",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gmail_thread_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional Gmail thread ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "match_score",
                    models.FloatField(
                        blank=True,
                        help_text="Match score to user preferences",
                        null=True,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="If user removes or hides posting"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
