# Generated by Django 5.1.4 on 2025-01-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_postings", "0002_alter_jobposting_fetched_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="gmail_message_id",
            field=models.CharField(
                default="unknown",
                help_text="Unique Gmail message ID if fetched from Gmail",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'Indeed', 'LinkedIn', 'Gmail', etc.",
                max_length=100,
                null=True,
            ),
        ),
    ]
