# Generated by Django 5.1.4 on 2025-01-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_postings", "0003_alter_jobposting_gmail_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
