# Generated by Django 5.1.4 on 2025-01-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_postings", "0004_jobposting_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="link",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="years_experience",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="application_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline to apply for the job.", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="benefits",
            field=models.TextField(
                blank=True,
                help_text="Overview of benefits offered by the company.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="company_logo_url",
            field=models.URLField(
                blank=True, help_text="URL to the company's logo image.", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="date_posted",
            field=models.DateTimeField(
                blank=True, help_text="Date when the job was posted.", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="employment_type",
            field=models.CharField(
                blank=True,
                help_text="Nature of employment (e.g., Full-time, Part-time, Contract, Internship).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="experience_level",
            field=models.CharField(
                blank=True,
                help_text="Required experience level (e.g., Junior, Mid-level, Senior).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="industries",
            field=models.CharField(
                blank=True,
                help_text="Relevant industries or sectors for the job.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="job_description_snippet",
            field=models.TextField(
                blank=True,
                help_text="A brief snippet from the job description.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="job_type",
            field=models.CharField(
                blank=True,
                help_text="Specific type of job (e.g., Remote, On-site, Hybrid).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Current status of the job posting (e.g., Actively Recruiting).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="company_name",
            field=models.TextField(
                blank=True, help_text="Name of the company offering the job.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="company_url",
            field=models.URLField(
                blank=True, help_text="URL to the company's website.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the job posting was created in the database.",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the job posting was soft-deleted.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="fetched_at",
            field=models.DateTimeField(
                help_text="Timestamp when the job posting was fetched from the source."
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="gmail_message_id",
            field=models.CharField(
                help_text="Unique Gmail message ID if fetched from Gmail.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="gmail_thread_id",
            field=models.CharField(
                blank=True,
                help_text="Optional Gmail thread ID.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the job posting has been soft-deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="location",
            field=models.TextField(
                blank=True, help_text="Location of the job.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="match_score",
            field=models.FloatField(
                blank=True, help_text="Match score to user preferences.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="salary",
            field=models.CharField(
                blank=True,
                help_text="Compensation details (e.g., $80,000 - $100,000).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="skills",
            field=models.JSONField(
                blank=True, help_text="List of required or preferred skills.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Source of the job posting (e.g., 'Indeed', 'LinkedIn', 'Gmail').",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Brief overview or key responsibilities of the job.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="title",
            field=models.TextField(help_text="Title of the job posting."),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the job posting was last updated in the database.",
            ),
        ),
    ]
