# Generated by Django 5.1.4 on 2025-01-30 20:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_postings", "0006_jobposting_job_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="job_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for each job posting.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="gmail_message_id",
            field=models.CharField(
                help_text="Unique Gmail message ID if fetched from Gmail.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="job_url",
            field=models.URLField(
                blank=True,
                help_text="Direct URL to the job posting.",
                null=True,
                unique=True,
            ),
        ),
    ]
