# Generated by Django 5.1.4 on 2025-01-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_postings", "0007_jobposting_job_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="job_url",
            field=models.URLField(
                blank=True, help_text="Direct URL to the job posting.", null=True
            ),
        ),
    ]
