# Generated by Django 5.1.4 on 2025-02-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_postings", "0009_alter_jobposting_job_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="job_url",
            field=models.URLField(
                blank=True,
                help_text="Direct URL to the job posting.",
                max_length=2000,
                null=True,
            ),
        ),
    ]
